[modules]
left = [ "Workspaces" ]
center = [ "WindowTitle" ]
right = [ [ "Tray", "MediaPlayer", "SystemInfo", "Clock", "Privacy", "Settings" ] ]

[system_info]
indicators = [ "Cpu", "Memory", "DownloadSpeed", "UploadSpeed", { Disk = "/" }, "IpAddress" ]

[settings]
lock_cmd = "playerctl --all-players pause; nixGL hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"